# Generated by Django 4.0.1 on 2022-01-19 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150, verbose_name='url')),
                ('content', models.TextField()),
                ('response', models.TextField()),
                ('status', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Действие 1'), (2, 'Действие 2'), (3, 'Действие 3'), (4, 'Действие 4'), (5, 'Действие 5')], null=True, verbose_name='Тип задачи')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
