# Generated by Django 4.0.1 on 2022-01-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_created_at_alter_task_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
