# Generated by Django 4.0.1 on 2022-02-16 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_task_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='package',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.task', verbose_name='Родитель'),
        ),
    ]
